# Site settings
title: Gabriel Fabrício
description: My Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fabriond.github.io/Resume/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gabriel Fabrício
user_description: I'm a young Software Engineer, always enthusiastic about learning new languages, algorithms and techniques. Mainly a web developer, I started with backend development, but am striving to become a full stack developer. I'm currently interested in learning Data Science and UI/UX design. 
user_title: Software Engineer
email: gfbf@ic.ufal.br
twitter_username: fabriond
github_username:  fabriond
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
